### PR TITLE
Update 5.34 Perl version to Fedora 36

### PR DESCRIPTION
**Pull request by michal-josef-spacek**

### CODE REVIEW

**Comment by michal-josef-spacek** [comment]
[test]

**Comment by michal-josef-spacek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by michal-josef-spacek** [comment]
[test-all]

**Comment by michal-josef-spacek** [comment]
[test]

**Review by zmiklank — APPROVED** [review]
Hi, sorry, this seems valid, as the EOL of F35 will be in a few days. However, do we want to leave the fedora version for 5.32 as it is (F34)?

**Comment by michal-josef-spacek** [comment]
@zmiklank Thanks you for your approval
For 5.32 I prepared PR: https://github.com/sclorg/s2i-perl-container/pull/262

**Pull request merged**
