### PR TITLE
use ct_init for initialization of the test environment

### PR DESCRIPTION
**Pull request by zmiklank**

### CODE REVIEW

**Comment by zmiklank** [comment]
[test-all]

**Comment by phracek** [comment]
It looks like we have again problem with RHEL7 and setup repo:

```
TASK [rhel : Install Copr] *****************************************************
task path: /var/ARTIFACTS/workdir-repository-None-g6qqdm0b/roles/rhel/tasks/main.yml:83
fatal: [root@10.31.13.173]: FAILED! => {"changed": true, "changes": {"installed": ["copr-cli"], "updated": []}, "msg": "http://download.devel.redhat.com/rel-eng/RCMTOOLS/latest-RCMTOOLS-2-RHEL-7/compose/BaseOS/x86_64/os/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found\nTrying other mirror.\nTo address this issue please refer to the below knowledge base article \n\nhttps://access.redhat.com/articles/1320623\n\nIf above article doesn't help to resolve this issue please open a ticket with Red Hat Support.\n\nhttp://download.devel.redhat.com/rel-eng/RCMTOOLS/latest-RCMTOOLS-2-RHEL-7/compose/BaseOS/x86_64/os/Packages/python2-ordered-set-2.0.2-3.el7eng.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found\nTrying other mirror.\n\n\nError downloading packages:\n  python2-ordered-set-2.0.2-3.el7eng.noarch: [Errno 256] No more mirrors to try.\n\n", "obsoletes": {"python-dateutil": {"dist": "noarch", "repo": "@anaconda/7.9", "version": "1.5-7.el7"}, "python-enum34": {"dist": "noarch", "repo": "@rhel", "version": "1.0.4-1.el7"}, "python-libcomps": {"dist": "x86_64", "repo": "@rcmtools", "version": "0.1.6-15.el7eng"}}, "rc": 1, "results": ["Loaded plugins: priorities, product-id, search-disabled-repos, subscription-\n              : manager\n\nThis system is not registered with an entitlement server. You can use subscription-manager to register.\n\n7923 packages excluded due to repository priority protections\nResolving Dependencies\n--> Running transaction check\n---> Package copr-cli.noarch 0:1.104-1.el7 will be installed\n--> Processing Dependency: python-copr >= 1.120.3.dev for package: copr-cli-1.104-1.el7.noarch\n--> Processing Dependency: /usr/bin/python3 for package: copr-cli-1.104-1.el7.noarch\n--> Processing Dependency: python-future for package: copr-cli-1.104-1.el7.noarch\n--> Processing Dependency: python-humanize for package: copr-cli-1.104-1.el7.noarch\n--> Processing Dependency: python-progress for package: copr-cli-1.104-1.el7.noarch\n--> Processing Dependency: python-simplejson for package: copr-cli-1.104-1.el7.noarch\n--> Running transaction check\n---> Package python-humanize.noarch 0:0.5.1-8.el7 will be installed\n---> Package python2-copr.noarch 0:1.124-1.el7 will be installed\n--> Processing Dependency: python-configparser for package: python2-copr-1.124-1.el7.noarch\n--> Processing Dependency: python-filelock for package: python2-copr-1.124-1.el7.noarch\n--> Processing Dependency: python-marshmallow for package: python2-copr-1.124-1.el7.noarch\n--> Processing Dependency: python-munch for package: python2-copr-1.124-1.el7.noarch\n--> Processing Dependency: python-requests-toolbelt for package: python2-copr-1.124-1.el7.noarch\n---> Package python2-future.noarch 0:0.18.2-2.el7 will be installed\n---> Package python2-progress.noarch 0:1.6-4.el7 will be installed\n---> Package python2-simplejson.x86_64 0:3.11.1-1.el7 will be installed\n---> Package python3.x86_64 0:3.6.8-18.el7 will be installed\n--> Processing Dependency: python3-libs(x86-64) = 3.6.8-18.el7 for package: python3-3.6.8-18.el7.x86_64\n--> Processing Dependency: python3-pip for package: python3-3.6.8-18.el7.x86_64\n--> Processing Dependency: python3-setuptools for package: python3-3.6.8-18.el7.x86_64\n--> Processing Dependency: libpython3.6m.so.1.0()(64bit) for package: python3-3.6.8-18.el7.x86_64\n--> Running transaction check\n---> Package python-configparser.noarch 0:4.0.2-2.el7 will be installed\n---> Package python-marshmallow.noarch 0:2.0.0-0.7.gita8b3385.el7 will be installed\n--> Processing Dependency: python-ordered-set for package: python-marshmallow-2.0.0-0.7.gita8b3385.el7.noarch\n---> Package python-munch.noarch 0:2.0.2-2.el7 will be installed\n---> Package python-requests-toolbelt.noarch 0:0.8.0-3.el7 will be installed\n---> Package python2-filelock.noarch 0:2.0.13-1.el7 will be installed\n---> Package python3-libs.x86_64 0:3.6.8-18.el7 will be installed\n---> Package python3-pip.noarch 0:9.0.3-8.el7 will be installed\n---> Package python3-setuptools.noarch 0:39.2.0-10.el7 will be installed\n--> Running transaction check\n---> Package python2-ordered-set.noarch 0:2.0.2-3.el7eng will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package               Arch   Version                  Repository          Size\n================================================================================\nInstalling:\n copr-cli              noarch 1.104-1.el7              epel                98 k\nInstalling for dependencies:\n python-configparser   noarch 4.0.2-2.el7              epel                41 k\n python-humanize       noarch 0.5.1-8.el7              epel                23 k\n python-marshmallow    noarch 2.0.0-0.7.gita8b3385.el7 epel                77 k\n python-munch          noarch 2.0.2-2.el7              epel                14 k\n python-requests-toolbelt\n                       noarch 0.8.0-3.el7              epel                78 k\n python2-copr          noarch 1.124-1.el7              epel                97 k\n python2-filelock      noarch 2.0.13-1.el7             epel                16 k\n python2-future        noarch 0.18.2-2.el7             epel               806 k\n python2-ordered-set   noarch 2.0.2-3.el7eng           rcmtools            12 k\n python2-progress      noarch 1.6-4.el7                epel                21 k\n python2-simplejson    x86_64 3.11.1-1.el7             epel               188 k\n python3               x86_64 3.6.8-18.el7             rhel-7-server-rpms  70 k\n python3-libs          x86_64 3.6.8-18.el7             rhel-7-server-rpms 6.9 M\n python3-pip           noarch 9.0.3-8.el7              rhel               1.6 M\n python3-setuptools    noarch 39.2.0-10.el7            rhel               629 k\n\nTransaction Summary\n================================================================================\nInstall  1 Package (+15 Dependent packages)\n\nTotal download size: 11 M\nInstalled size: 53 M\nDownloading packages:\n"]}
```

The repository is wrong. BaseOS is not valid for RHEL-7. Please file a ticket to TMT.

**Comment by zmiklank** [comment]
> TASK [rhel : Install Copr] *****************************************************
> task path: /var/ARTIFACTS/workdir-repository-None-g6qqdm0b/roles/rhel/tasks/main.yml:83
> fatal: [root@10.31.13.173]: FAILED! => {"changed": true, "changes": {"installed": ["copr-cli"], "updated": []}, "msg": "http://download.devel.redhat.com/rel-eng/RCMTOOLS/latest-RCMTOOLS-2-RHEL-7/compose/BaseOS/x86_64/os/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found\nTrying other mirror.\nTo address this issue please refer to the below knowledge base article \n\nhttps://access.redhat.com/articles/1320623\n\nIf above article doesn't help to resolve this issue please open a ticket with Red Hat Support.\n\nhttp://download.devel.redhat.com/rel-eng/RCMTOOLS/latest-RCMTOOLS-2-RHEL-7/compose/BaseOS/x86_64/os/Packages/python2-ordered-set-2.0.2-3.el7eng.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found\nTrying other mirror.\n\n\nError downloading packages:\n  python2-ordered-set-2.0.2-3.el7eng.noarch: [Errno 256] No more mirrors to try.\n\n", "obsoletes": {"python-dateutil": {"dist": "noarch", "repo": "@anaconda/7.9", "version": "1.5-7.el7"}, "python-enum34": {"dist": "noarch", "repo": "@rhel", "version": "1.0.4-1.el7"}, "python-libcomps": {"dist": "x86_64", "repo": "@rcmtools", "version": "0.1.6-15.el7eng"}}, "rc": 1, "results": ["Loaded plugins: priorities, product-id, search-disabled-repos, subscription-\n              : manager\n\nThis system is not registered with an entitlement server. You can use subscription-manager to register.\n\n7923 packages excluded due to repository priority protections\nResolving Dependencies\n--> Running transaction check\n---> Package copr-cli.noarch 0:1.104-1.el7 will be installed\n--> Processing Dependency: python-copr >= 1.120.3.dev for package: copr-cli-1.104-1.el7.noarch\n--> Processing Dependency: /usr/bin/python3 for package: copr-cli-1.104-1.el7.noarch\n--> Processing Dependency: python-future for package: copr-cli-1.104-1.el7.noarch\n--> Processing Dependency: python-humanize for package: copr-cli-1.104-1.el7.noarch\n--> Processing Dependency: python-progress for package: copr-cli-1.104-1.el7.noarch\n--> Processing Dependency: python-simplejson for package: copr-cli-1.104-1.el7.noarch\n--> Running transaction check\n---> Package python-humanize.noarch 0:0.5.1-8.el7 will be installed\n---> Package python2-copr.noarch 0:1.124-1.el7 will be installed\n--> Processing Dependency: python-configparser for package: python2-copr-1.124-1.el7.noarch\n--> Processing Dependency: python-filelock for package: python2-copr-1.124-1.el7.noarch\n--> Processing Dependency: python-marshmallow for package: python2-copr-1.124-1.el7.noarch\n--> Processing Dependency: python-munch for package: python2-copr-1.124-1.el7.noarch\n--> Processing Dependency: python-requests-toolbelt for package: python2-copr-1.124-1.el7.noarch\n---> Package python2-future.noarch 0:0.18.2-2.el7 will be installed\n---> Package python2-progress.noarch 0:1.6-4.el7 will be installed\n---> Package python2-simplejson.x86_64 0:3.11.1-1.el7 will be installed\n---> Package python3.x86_64 0:3.6.8-18.el7 will be installed\n--> Processing Dependency: python3-libs(x86-64) = 3.6.8-18.el7 for package: python3-3.6.8-18.el7.x86_64\n--> Processing Dependency: python3-pip for package: python3-3.6.8-18.el7.x86_64\n--> Processing Dependency: python3-setuptools for package: python3-3.6.8-18.el7.x86_64\n--> Processing Dependency: libpython3.6m.so.1.0()(64bit) for package: python3-3.6.8-18.el7.x86_64\n--> Running transaction check\n---> Package python-configparser.noarch 0:4.0.2-2.el7 will be installed\n---> Package python-marshmallow.noarch 0:2.0.0-0.7.gita8b3385.el7 will be installed\n--> Processing Dependency: python-ordered-set for package: python-marshmallow-2.0.0-0.7.gita8b3385.el7.noarch\n---> Package python-munch.noarch 0:2.0.2-2.el7 will be installed\n---> Package python-requests-toolbelt.noarch 0:0.8.0-3.el7 will be installed\n---> Package python2-filelock.noarch 0:2.0.13-1.el7 will be installed\n---> Package python3-libs.x86_64 0:3.6.8-18.el7 will be installed\n---> Package python3-pip.noarch 0:9.0.3-8.el7 will be installed\n---> Package python3-setuptools.noarch 0:39.2.0-10.el7 will be installed\n--> Running transaction check\n---> Package python2-ordered-set.noarch 0:2.0.2-3.el7eng will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package               Arch   Version                  Repository          Size\n================================================================================\nInstalling:\n copr-cli              noarch 1.104-1.el7              epel                98 k\nInstalling for dependencies:\n python-configparser   noarch 4.0.2-2.el7              epel                41 k\n python-humanize       noarch 0.5.1-8.el7              epel                23 k\n python-marshmallow    noarch 2.0.0-0.7.gita8b3385.el7 epel                77 k\n python-munch          noarch 2.0.2-2.el7              epel                14 k\n python-requests-toolbelt\n                       noarch 0.8.0-3.el7              epel                78 k\n python2-copr          noarch 1.124-1.el7              epel                97 k\n python2-filelock      noarch 2.0.13-1.el7             epel                16 k\n python2-future        noarch 0.18.2-2.el7             epel               806 k\n python2-ordered-set   noarch 2.0.2-3.el7eng           rcmtools            12 k\n python2-progress      noarch 1.6-4.el7                epel                21 k\n python2-simplejson    x86_64 3.11.1-1.el7             epel               188 k\n python3               x86_64 3.6.8-18.el7             rhel-7-server-rpms  70 k\n python3-libs          x86_64 3.6.8-18.el7             rhel-7-server-rpms 6.9 M\n python3-pip           noarch 9.0.3-8.el7              rhel               1.6 M\n python3-setuptools    noarch 39.2.0-10.el7            rhel               629 k\n\nTransaction Summary\n================================================================================\nInstall  1 Package (+15 Dependent packages)\n\nTotal download size: 11 M\nInstalled size: 53 M\nDownloading packages:\n"]}

These logs are from January the 16th. It could have been fixed meanwhile.

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test-openshift]

**Review by phracek — CHANGES_REQUESTED** [review]
RHEL7 tests are failing on TMT plans:

```
TASK [container-test-utils : Make sure tools we need for containers tests are available (EL8 and further)] ***
task path: /var/ARTIFACTS/workdir-repository-None-ipjqbkbo/roles/container-test-utils/tasks/main.yml:16
failed: [root@10.31.10.213] (item=podman-docker) => {"ansible_loop_var": "item", "changed": false, "changes": {"installed": ["podman-docker"]}, "item": "podman-docker", "msg": "Error: podman-docker conflicts with 2:docker-1.13.1-209.git7d71120.el7_9.x86_64\n", "rc": 1, "results": ["Loaded plugins: priorities, product-id, search-disabled-repos, subscription-\n              : manager\n\nThis system is not registered with an entitlement server. You can use subscription-manager to register.\n\n7925 packages excluded due to repository priority protections\nResolving Dependencies\n--> Running transaction check\n---> Package podman-docker.noarch 0:1.6.4-36.el7_9 will be installed\n--> Processing Dependency: podman = 1.6.4-36.el7_9 for package: podman-docker-1.6.4-36.el7_9.noarch\n--> Running transaction check\n---> Package podman.x86_64 0:1.6.4-36.el7_9 will be installed\n--> Processing Dependency: containernetworking-plugins >= 0.8.1-1 for package: podman-1.6.4-36.el7_9.x86_64\n--> Processing Dependency: conmon for package: podman-1.6.4-36.el7_9.x86_64\n--> Processing Dependency: nftables for package: podman-1.6.4-36.el7_9.x86_64\n--> Running transaction check\n---> Package conmon.x86_64 2:2.0.15-1.el7_8 will be installed\n---> Package containernetworking-plugins.x86_64 0:0.8.3-3.el7_8 will be installed\n---> Package nftables.x86_64 1:0.8-14.el7 will be installed\n--> Processing Dependency: libnftnl.so.7(LIBNFTNL_5)(64bit) for package: 1:nftables-0.8-14.el7.x86_64\n--> Processing Dependency: libnftnl.so.7()(64bit) for package: 1:nftables-0.8-14.el7.x86_64\n--> Running transaction check\n---> Package libnftnl.x86_64 0:1.0.8-3.el7 will be installed\n--> Processing Conflict: podman-docker-1.6.4-36.el7_9.noarch conflicts docker\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}
```

**Comment by zmiklank** [comment]
> RHEL7 tests are failing on TMT plans:
> 
> ```
> TASK [container-test-utils : Make sure tools we need for containers tests are available (EL8 and further)] ***
> task path: /var/ARTIFACTS/workdir-repository-None-ipjqbkbo/roles/container-test-utils/tasks/main.yml:16
> failed: [root@10.31.10.213] (item=podman-docker) => {"ansible_loop_var": "item", "changed": false, "changes": {"installed": ["podman-docker"]}, "item": "podman-docker", "msg": "Error: podman-docker conflicts with 2:docker-1.13.1-209.git7d71120.el7_9.x86_64\n", "rc": 1, "results": ["Loaded plugins: priorities, product-id, search-disabled-repos, subscription-\n              : manager\n\nThis system is not registered with an entitlement server. You can use subscription-manager to register.\n\n7925 packages excluded due to repository priority protections\nResolving Dependencies\n--> Running transaction check\n---> Package podman-docker.noarch 0:1.6.4-36.el7_9 will be installed\n--> Processing Dependency: podman = 1.6.4-36.el7_9 for package: podman-docker-1.6.4-36.el7_9.noarch\n--> Running transaction check\n---> Package podman.x86_64 0:1.6.4-36.el7_9 will be installed\n--> Processing Dependency: containernetworking-plugins >= 0.8.1-1 for package: podman-1.6.4-36.el7_9.x86_64\n--> Processing Dependency: conmon for package: podman-1.6.4-36.el7_9.x86_64\n--> Processing Dependency: nftables for package: podman-1.6.4-36.el7_9.x86_64\n--> Running transaction check\n---> Package conmon.x86_64 2:2.0.15-1.el7_8 will be installed\n---> Package containernetworking-plugins.x86_64 0:0.8.3-3.el7_8 will be installed\n---> Package nftables.x86_64 1:0.8-14.el7 will be installed\n--> Processing Dependency: libnftnl.so.7(LIBNFTNL_5)(64bit) for package: 1:nftables-0.8-14.el7.x86_64\n--> Processing Dependency: libnftnl.so.7()(64bit) for package: 1:nftables-0.8-14.el7.x86_64\n--> Running transaction check\n---> Package libnftnl.x86_64 0:1.0.8-3.el7 will be installed\n--> Processing Conflict: podman-docker-1.6.4-36.el7_9.noarch conflicts docker\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}
> ```

I think that is the same problem we had in composes for openshift tests. I think you fixed it with manually removing podman in the tmt plan?

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
[test]

**Review by phracek — APPROVED** [review]
LGTM. Thanks for the PR.

**Pull request merged**
