### PR TITLE
Deprecate perl-5.26 imagestreams for RHEL7 and CentOS7

### PR DESCRIPTION
**Pull request by phracek**
Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by ppisar** [comment]
rh-perl526 software collection for RHEL 7 is supported up to May 2021
<https://access.redhat.com/support/policy/updates/rhscl-rhel7>. Isn't
too early for removing it from OpenShift templates? Otherwise I have no
problems with this patch from Perl point of view.

**Comment by pkubatrh** [comment]
@ppisar  The reason we are doing it early is so that it does not end up in the next release of Openshift after the images are EOL (the imagestream sync will be done some time before GA).

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by phracek** [comment]
Let's one more try.

[test-openshift]

**Pull request merged**
