### PR TITLE
Add aarch64 imagestreams

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by ppisar** [comment]
No issue from Perl point of view.

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by rhscl-automation-poll** [comment]
Can one of the admins verify this patch?

**Comment by hhorak** [comment]
Import of perl-rhel-aarch64.json works.
[test]

**Comment by hhorak** [comment]
Imagestream check does not work for 5.30 because perl-rhel-aarch64.json does not contain it on purpose (aarch64 only contain el8 images, and 5.30 is no available on el8 yet). Merging anyway, because this test issue should not block the imagestream update.

**Pull request merged**
