### PR TITLE
Fix test_from_dockerfile() exit code check

### PR DESCRIPTION
**Pull request by michal-josef-spacek**
If second test in test_from_dockerfile() fails, test pass still before
this change.

### CODE REVIEW

**Review by phracek — APPROVED** [review]
LGTM, Thanks for the PR.

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-openshift]

**Comment by zmiklank** [comment]
[test-openshift]

**Review by zmiklank — APPROVED** [review]
The test failures are not related, as my PR https://github.com/sclorg/s2i-perl-container/pull/228 failed that way too.

**Pull request merged**
