### PR TITLE
Remove 5.26-ubi8 imagestreams

### PR DESCRIPTION
**Pull request by yselkowitz**

### CODE REVIEW

**Comment by yselkowitz** [comment]
https://github.com/sclorg/dancer-ex/tree/master/openshift/templates needs to be moved to 5.30-ubi8 first.

**Comment by phracek** [comment]
@yselkowitz I do not know, why you remove 5.26 imagestream, which does not have EOL.

[test][test-openshift-4][test-openshift]

**Comment by yselkowitz** [comment]
https://catalog.redhat.com/software/containers/ubi8/perl-526/5c83998abed8bd28d0e74c0f says otherwise? :shrug:

**Comment by phracek** [comment]
perl-5.26 container is still supported. Closing this issue. Comment is updated https://catalog.redhat.com/software/containers/ubi8/perl-526/5c83998abed8bd28d0e74c0f

**Pull request closed without merging**
