### PR TITLE
Enable testing Perl 5.36

### PR DESCRIPTION
**Pull request by jplesnik**

### CODE REVIEW

**Review by phracek — APPROVED** [review]
Everything LGTM. THanks for this pull request and add new Perl version.

**Comment by zmiklank** [comment]
Do not we want to add perl 5.36 also to build and push action?

**Comment by phracek** [comment]
Adding new version to container mean, that `build-and-push-action` is modified as well.

**Comment by zmiklank** [comment]
Yes, it will be failing until the version is added, but this is standard practice. The python container does it in this moment too.
It does not really matter though if you'll remember to add it later.

**Pull request merged**
