### PR TITLE
use ct_init for modfcgid

### PR DESCRIPTION
**Pull request by zmiklank**
We already use `ct_init` in `test/run`. This PR adds `ct_init` also to `test/run-modfcgid`.

+ use generic function for 'wait for pid' and 'check result'.

### CODE REVIEW

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
[test]

**Comment by phracek** [comment]
[test-all]

**Review by phracek — APPROVED** [review]
Everything LGTM. Let's see if tests are passing.

**Pull request merged**
