### PR TITLE
Test latest_imagestreams to OpenShift 4 as well.

### PR DESCRIPTION
**Pull request by phracek**
This pull request adds test called `test_latest_imagestreams` also for OpenShift 4 case.

### CODE REVIEW

**Comment by phracek** [comment]
Running OpenShift tests. Container tests are not needed to be executed.

[test-openshift]

**Review by zmiklank — APPROVED** [review]

**Comment by phracek** [comment]
OpenShift 3 cluster did not start properly.


```bash
Checking if OpenShift client is configured properly ...
Checking if image registry.redhat.io/openshift3/ose-control-plane:v3.11 is available ...
Starting OpenShift using registry.redhat.io/openshift3/ose-control-plane:v3.11 ...
I1108 06:59:51.072681   18660 config.go:40] Running "create-master-config"
I1108 06:59:55.098817   18660 config.go:46] Running "create-node-config"
I1108 06:59:56.221907   18660 flags.go:30] Running "create-kubelet-flags"
I1108 06:59:56.704952   18660 run_kubelet.go:49] Running "start-kubelet"
I1108 06:59:56.907962   18660 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I1108 07:00:38.921583   18660 interface.go:26] Installing "kube-proxy" ...
I1108 07:00:38.922346   18660 interface.go:26] Installing "kube-dns" ...
I1108 07:00:38.922360   18660 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I1108 07:00:38.922370   18660 interface.go:26] Installing "openshift-apiserver" ...
I1108 07:00:38.922415   18660 apply_template.go:81] Installing "openshift-apiserver"
I1108 07:00:38.922675   18660 apply_template.go:81] Installing "kube-proxy"
I1108 07:00:38.923693   18660 apply_template.go:81] Installing "kube-dns"
I1108 07:00:38.923907   18660 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I1108 07:00:45.387910   18660 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: timed out waiting for the condition
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.

OpenShift tests for rhscl/perl-530-rhel7:5.30 failed.
errexit on line 63, common/test.sh
```

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
RHEL7 OpenShift 3 test failed on the reason, that cluster did not start up properly.

```bash
Checking if image registry.redhat.io/openshift3/ose-control-plane:v3.11 is available ...
Starting OpenShift using registry.redhat.io/openshift3/ose-control-plane:v3.11 ...
I1109 07:41:27.387895   18667 config.go:40] Running "create-master-config"
I1109 07:41:30.714285   18667 config.go:46] Running "create-node-config"
I1109 07:41:31.601899   18667 flags.go:30] Running "create-kubelet-flags"
I1109 07:41:32.074676   18667 run_kubelet.go:49] Running "start-kubelet"
I1109 07:41:32.285010   18667 run_self_hosted.go:181] Waiting for the kube-apiserver to be ready ...
I1109 07:42:12.298955   18667 interface.go:26] Installing "kube-proxy" ...
I1109 07:42:12.299615   18667 interface.go:26] Installing "kube-dns" ...
I1109 07:42:12.299626   18667 interface.go:26] Installing "openshift-service-cert-signer-operator" ...
I1109 07:42:12.299638   18667 interface.go:26] Installing "openshift-apiserver" ...
I1109 07:42:12.299670   18667 apply_template.go:81] Installing "openshift-apiserver"
I1109 07:42:12.300548   18667 apply_template.go:81] Installing "kube-proxy"
I1109 07:42:12.300637   18667 apply_template.go:81] Installing "kube-dns"
I1109 07:42:12.301619   18667 apply_template.go:81] Installing "openshift-service-cert-signer-operator"
I1109 07:42:17.982192   18667 interface.go:41] Finished installing "kube-proxy" "kube-dns" "openshift-service-cert-signer-operator" "openshift-apiserver"
Error: timed out waiting for the condition
error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --config
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.

OpenShift tests for rhscl/perl-530-rhel7:5.30 failed.
errexit on line 63, common/test.sh
```

**Pull request merged**
