### PR TITLE
add jenkins badge

### PR DESCRIPTION
**Pull request by PI-Victor**
@hhorak cc

### CODE REVIEW

**Comment by bparees** [comment]
This (and the other ones) should not be merged. That job is run to test PRs, it doesn't reflect the state of master, it reflects the state of the last pr that was tested.

**Comment by hhorak** [comment]
I already merged mongodb one (not others) before reading the comment above. So what we would need is to have a separate job for testing master, right? (not sure about Jenkins details, whether we can distinguish it within one job, common for PR and master)

**Comment by bparees** [comment]
If you want a status badge, yes. Or the badge could be based on our push
images job which would indicate we've successfully built and pushed master
of all the repos, except that job doesn't build or push the latest rhel
images, so it's not a full source of truth. Also it isn't guaranteed to
have run on master yet since it runs hourly or so, so the badge could
indicate success when things were broken.

Overall I don't see much point in status badges like this.

Ben Parees | OpenShift

**Comment by PI-Victor** [comment]
@bparees i've reverted this change now and submitted a PR, in my defense i did check the details on the jenkins page twice and it seemed ok with me, but i was clearly wrong.

**Pull request closed without merging**
