### PR TITLE
Switch Perl 5.32 to Fedora 36

### PR DESCRIPTION
**Pull request by michal-josef-spacek**
With usage of Perl module stream in Fedora 36

### CODE REVIEW

**Comment by michal-josef-spacek** [comment]
[test]

**Comment by michal-josef-spacek** [comment]
[test-all]

**Comment by zmiklank** [comment]
Thank you for the PR. Could you please explain to me briefly, why are those modules-related changes needed?

**Comment by michal-josef-spacek** [comment]
We discussed with Jitka and 5.32 is deprecated in Fedora. I am closing this PR.

**Pull request closed without merging**
