### PR TITLE
Replace 'template.openshift.io' with 'openshift.io'

### PR DESCRIPTION
**Pull request by pvalena**
https://github.com/openshift/origin/pull/17922#pullrequestreview-86819501

### CODE REVIEW

**Comment by ppisar** [comment]
Fine.

**Comment by pvalena** [comment]
```
14:53:06 Error downloading packages:
14:53:06   rh-perl524-perl-CPAN-2.11-368.el7.noarch: [Errno 256] No more mirrors to try.
```

**Comment by pvalena** [comment]
[test]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pvalena** [comment]
Thanks!

**Pull request merged**
