### PR TITLE
Deprecate perl-5.26 which reached EOL in May 2021

### PR DESCRIPTION
**Pull request by phracek**

### CODE REVIEW

**Comment by phracek** [comment]
[test][test-openshift-4]

**Comment by phracek** [comment]
OpenShift 4 test is failing on network issues.
Cluster seems to be not available ATM.
```bash
Kubernetes Version: v1.19.0+a5a0987
error: Invalid status code (504): 504 Gateway Timeout
OpenShift tests <span class="pl-k">for</span> rhscl/perl-530-rhel7:5.30 failed.
```

I will try it later on.

**Comment by pkubatrh** [comment]
perl 5.26 is supported for the whole lifetime of RHEL8, pretty sure we do not want to deprecate it now

**Comment by jplesnik** [comment]
Support of perl 5.24 ends in May 2021.

**Comment by phracek** [comment]
> Support of perl 5.24 ends for RHEL 8 in May 2021.

perl-5.24 is not building at all. https://github.com/sclorg/s2i-perl-container/blob/master/Makefile#L3

**Comment by phracek** [comment]
[test][test-openshift-4]

**Comment by phracek** [comment]
[test][test-openshift-4]

**Comment by michal-josef-spacek** [comment]
[test]

**Comment by jplesnik** [comment]
[test][test-openshift-4]

**Comment by phracek** [comment]
[test-openshift]

**Comment by hhorak** [comment]
LGTM

**Pull request merged**
