### PR TITLE
Use a function from test-lib.sh for checking result and other actions

### PR DESCRIPTION
**Pull request by hhorak**
**Warning: this requires https://github.com/sclorg/container-common-scripts/pull/238 to be merged first.**

Avoids unnecessary code duplication

### CODE REVIEW

**Comment by hhorak** [comment]
[test]

**Comment by michal-josef-spacek** [comment]
This is affected by issue fixed in https://github.com/sclorg/container-common-scripts/pull/241

**Comment by michal-josef-spacek** [comment]
There is something bad:
Tested on `make test TARGET=fedora VERSIONS=5.30 TESTS=test_sample_test_app`
# Old results:
### Preparing
* [INFO] Starting tests for sample-test-app...
* [INFO] Build the test application image...
* [INFO] Testing 's2i usage'...
* [INFO] Testing 'docker run' usage...
### First test
* [INFO] Waiting for application container to start...
* [INFO] Testing the image SCL enable...
* [INFO] Testing the HTTP response for <http://172.17.0.2:8080/>...
* [INFO] Cleaning up the test application...
### Second test
* [INFO] Waiting for application container to start...
* [INFO] Testing the image SCL enable...
* [INFO] Testing the HTTP response for <http://172.17.0.2:8080/>...
* [INFO] Cleaning up the test application...
### Cleaning
* [INFO] All tests for the sample-test-app finished successfully....
* [INFO] Cleaning up the test application image...

# New results (after this PR)
* [INFO] Starting tests for sample-test-app...
* [INFO] Build the test application image...
* [INFO] Testing 's2i usage'...
* [INFO] Testing 'docker run' usage...
* [INFO] Testing the image SCL enable...
* [INFO] Testing the image SCL enable...
 STDERR
 docker: Container ID file found, make sure the other container isn't running or delete 
 /tmp/tmp.2tYtOhtZV4perl_test_cidfiles/sample-test-app.
 See 'docker run --help'.
* [INFO] All tests for the sample-test-app finished successfully....
* [INFO] Cleaning up the test application image...

**Comment by hhorak** [comment]
Thanks for spotting the issue, @michal-josef-spacek. Hope it's fixed now.

**Comment by phracek** [comment]
[test-all]

**Review by phracek — APPROVED** [review]
LGTM

**Comment by hhorak** [comment]
[test]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
Everything is passing. We CAN merge it.

**Comment by phracek** [comment]
The result tests for CentOS 7 look like:

```bash
===============================================
Test cases results:

 [PASSED] for 'appnamenotset' test_sample_test_app (00:00:10)
 [PASSED] for 'appnamenotset' test_binpath (00:00:05)
 [PASSED] for 'appnamenotset' test_psgi (00:00:47)
 [PASSED] for 'appnamenotset' test_psgi_variables (00:00:46)
 [PASSED] for 'appnamenotset' test_warningonstderr (00:00:03)
 [PASSED] for 'appnamenotset' test_npm (00:00:07)
 [PASSED] for 'appnamenotset' test_from_dockerfile (00:03:29)
 [PASSED] for 'appnamenotset' test_scl_variables_in_dockerfile (00:00:03)

Tests for quay.io/centos7/perl-530-centos7:5.30 succeeded.
```

Awesome work.

**Pull request merged**
