### PR TITLE
Add support for testing imagestreams on RHEL9 host

### PR DESCRIPTION
**Pull request by phracek**

### CODE REVIEW

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test-all]

**Comment by phracek** [comment]
RHEL9 OpenShift 4 tests for version `5.32` passed:

```bash
-----------------------------------------------
Running test test_perl_imagestream (starting at 2022-10-18 09:13:16+02:00) ... 
-----------------------------------------------
Testing perl imagestream application
Running image stream test for stream test/imagestreams/perl-rhel.json and quickstart template test/sample-test-app.json
Image name is ubi9/perl-532:1
Now using project "sclorg-test-25354" on server "https://api.core-serv-ocp.hosted.psi.rdu2.redhat.com:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app rails-postgresql-example

to build a new example application in Ruby. Or use kubectl to deploy a simple Kubernetes application:

    kubectl create deployment hello-node --image=k8s.gcr.io/e2e-test-images/agnhost:2.33 -- /agnhost serve-hostname

secret/6340056-core-services-apps-ci-pull-secret created
imagestream.image.openshift.io/perl created
Creating project skipped.
Uploading image ubi9/perl-532:1 as perl:5.32 into OpenShift internal registry.
OCP4 loging address is default-route-openshift-image-registry.apps.core-serv-ocp.hosted.psi.rdu2.redhat.com.
Login Succeeded!
Login to default-route-openshift-image-registry.apps.core-serv-ocp.hosted.psi.rdu2.redhat.com was successfully.
Getting image source signatures
Copying blob sha256:7f2ebeb5a53447d9370f743969eafb7655c7e317fcedd1466ccae6c13bfb910a
Copying blob sha256:efa04bf9c8ac0ff97961846c9b374cdfbf286159cc00a49721f8ec617d37563d
Copying blob sha256:a5db80d6a8f6ab1c22b3c720df5089a184c3a00f974aa441a4505ed37c218f9e
Copying blob sha256:217e03878b825cb8d0a735b7dd59b49a8bd654013edea5de369c5950b7bfafb2
Copying blob sha256:787a928b4bab22cc8f2fe9d5fcf8504e77822d7f117132247080fd3d892c245c
Copying blob sha256:c043b38e70c6efb963da6e0ff0b0941d550e45d834c86aa8bb89272ad707cd55
Copying blob sha256:45c827b1946c6ea666d19cb635d7f103a0699426c8964fe0042328b178caced1
Copying blob sha256:8c2e9c7e0ad0e206f46f2a30d8021ceb799d7516253f589fb34fe1c6ed4973b4
Copying config sha256:65c53c44b8ce26526fe5382eba4686dbe95844446ea3e4fc20051b49933fde5e
Writing manifest to image destination
Storing signatures
Creating a new-app with name perl in namespace sclorg-test-25354 with args -p SOURCE_REPOSITORY_REF=staging -p VERSION=5.32-ubi9 -p NAME=perl-testing -p NAMESPACE=sclorg-test-25354.
warning: Template parameter "NAMESPACE" was overwritten
W1018 09:13:35.766005   22058 shim_kubectl.go:58] Using non-groupfied API resources is deprecated and will be removed in a future release, update apiVersion to "template.openshift.io/v1" for your resource
--> Deploying template "sclorg-test-25354/sample-test-app" for "/var/tmp/test-input-xNC1k0.json" to project sclorg-test-25354

[snipped]

--> Creating resources ...
    service "perl-testing" created
    route.route.openshift.io "perl-testing" created
    imagestream.image.openshift.io "perl-testing" created
    buildconfig.build.openshift.io "perl-testing" created
    deploymentconfig.apps.openshift.io "perl-testing" created
--> Success
    Access your application via route 'perl-testing-sclorg-test-25354.apps.core-serv-ocp.hosted.psi.rdu2.redhat.com' 
    Build scheduled, use 'oc logs -f buildconfig/perl-testing' to track its progress.
    Run 'oc status' to view your app.
perl-testing-1-build
Waiting for perl-testing build pod to finish ............ DONE
Waiting for perl-testing pod becoming ready ....... DONE
  Checking APP using ct_os_test_response_internal 'http://172.30.237.168:8080' '200' 'Everything is OK' ...
command POD not running yet, will start one called command-app registry.access.redhat.com/ubi7/ubi
pod/command-app created
Waiting for command POD .NAME                    READY   STATUS              RESTARTS   AGE
command-app             0/1     ContainerCreating   0          85s
perl-testing-1-build    0/1     Completed           0          2m13s
perl-testing-1-deploy   0/1     Completed           0          100s
perl-testing-1-t2lq8    1/1     Running             0          97s
.NAME                    READY   STATUS      RESTARTS   AGE
command-app             1/1     Running     0          4s
perl-testing-1-build    0/1     Completed   0          52s
perl-testing-1-deploy   0/1     Completed   0          19s
perl-testing-1-t2lq8    1/1     Running     0          16s
DONE
  Information about the image we work with:
      lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/sclorg-test-25354/perl-

[snipped]

  creationTimestamp: "2022-10-18T07:10:54Z"
  name: perl-testing@sha256:af73375f47d7273961a981ca69a42ec05aaaa0c8493312756b729b4d09076a2d
  namespace: sclorg-test-25354
  Check passed.
Deleting project skipped, cleaning objects only.
```

**Review by zmiklank — APPROVED** [review]

**Pull request merged**
