### PR TITLE
Run all tests and reports failures at the end

### PR DESCRIPTION
**Pull request by phracek**
Run all tests and reports failures at the end.

The commit executes all tests and reports
at the end result in format like:

[PASSED] test_sample_test_app
[PASSED] test_binpath
[PASSED] test_psgi
[PASSED] test_psgi_variables
[PASSED] test_warningonstderr
[PASSED] test_npm

Tests for rhscl/perl-526-rhel7 succeeded.

Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test-openshift]

**Comment by ppisar** [comment]
I doubt it will work. the do_test() invocation sets test_name variable from its first argument and the variable is used in in run_s2i_build() to build an application image from the proper sources found in the same-named directory. Your patch removes the do_test() invocations and thus I believe the tests won't build the intended application images and will fail.

**Comment by ppisar** [comment]
I got confused by renaming the test function. It looks good.

**Pull request merged**
