### PR TITLE
Add version 5.26

### PR DESCRIPTION
**Pull request by pkubatrh**
The centos build will fail for now as the `rh-perl526-perl-Apache-Reload` is yet to be rebuilt, but the code can be ready in this PR until it is available.

### CODE REVIEW

**Comment by ppisar** [comment]
Thank you for the pull request, but I have already made all necessary changes. But not yet pushed because of CentOS lacking the builds.

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
[test-openshift]

**Comment by hhorak** [comment]
It seems like the openshift tests only fail because there is no new app in the master yet, which should be fixed after merging. So, merging :) THANKS!

**Pull request merged**
