### PR TITLE
Deprecate version 5.20

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by omron93** [comment]
Thanks.

**Comment by ppisar** [comment]
The Makefile should move 5.20 from VERSIONS variable to OPENSHIFT_NAMESPACES
variable. The patch removes it instead. OpenShift wants to offer deprecated
images to its users.

**Comment by pkubatrh** [comment]
To be honest I do not think the `OPENSHIFT_NAMESPACES` variable is even used for anything anymore

**Comment by omron93** [comment]
`OPENSHIFT_NAMESPACES` was used to pick images which should have `openshift/` namespace. Later images now have `centos/` namespace.

**Pull request merged**
