### PR TITLE
Enable building and testing Perl 5.40 in C10S

### PR DESCRIPTION
**Pull request by phracek**
This pull request enables building and testing Perl 5.40 container in C10S

The pull request is separated into several commits:

1) git move 5.38 to 5.40
2) Copy sources back to 5.38 and commit
3) Fix symlinks in test directory
4) Copy Dockerfile.c9s to Dockerfile.c10s
5) Make Dockerfiles a bit similar
6) Fix Test suite
7) Update Documentation and enable 5.40 in Makefile
8) Update build-and-push action

### CODE REVIEW

**Comment by phracek** [comment]
Differences between Dockerfiles for faster analysis.

Difference between Fedora and C10S:

```
$ diff -u Dockerfile.fedora Dockerfile.c10s
--- Dockerfile.fedora	2024-08-09 12:44:04
+++ Dockerfile.c10s	2024-08-09 12:45:28
@@ -1,15 +1,13 @@
-FROM quay.io/fedora/s2i-base:40
+FROM quay.io/sclorg/s2i-base-c10s:c10s

 # This image provides a Perl 5.40 environment you can use to run your Perl applications.
+
 EXPOSE 8080

 # Image metadata
 ENV PERL_VERSION=5.40 \
     PERL_SHORT_VER=540 \
-    VERSION=0 \
-    NAME=perl \
-    PATH=/opt/app-root/src/extlib/bin:$PATH \
-    PERL5LIB=/opt/app-root/src/extlib/lib/perl5
+    NAME=perl

 ENV SUMMARY="Platform for building and running Perl $PERL_VERSION applications" \
     DESCRIPTION="Perl $PERL_VERSION available as container is a base platform for \
@@ -25,18 +23,21 @@
       io.k8s.description="$DESCRIPTION" \
       io.k8s.display-name="Apache 2.4 with mod_fcgid and Perl $PERL_VERSION" \
       io.openshift.expose-services="8080:http" \
-      io.openshift.tags="builder,${NAME},${NAME}${PERL_SHORT_VER}" \
+      io.openshift.tags="builder,${NAME},${NAME}${PERL_SHORT_VER}","${NAME}-${PERL_SHORT_VER}" \
       io.openshift.s2i.scripts-url="image:///usr/libexec/s2i" \
       io.s2i.scripts-url="image:///usr/libexec/s2i" \
-      name="fedora/$NAME-$PERL_SHORT_VER" \
-      com.redhat.component="$NAME" \
-      version="$VERSION" \
+      name="sclorg/${NAME}-${PERL_SHORT_VER}-c10s" \
+      com.redhat.component="${NAME}-${PERL_SHORT_VER}-container" \
+      version="1" \
+      com.redhat.license_terms="https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI" \
       maintainer="SoftwareCollections.org <sclorg@redhat.com>" \
       help="For more information visit https://github.com/sclorg/s2i-${NAME}-container" \
-      usage="s2i build <SOURCE-REPOSITORY> quay.io/fedora/$NAME-$PERL_SHORT_VER <APP-NAME>"
+      usage="s2i build <SOURCE-REPOSITORY> quay.io/sclorg/${NAME}-${PERL_SHORT_VER}-c10s:latest <APP-NAME>"

+# Deselect a default stream
 RUN INSTALL_PKGS="perl perl-devel mod_fcgid perl-App-cpanminus perl-FCGI patch" && \
-    dnf install -y --setopt=tsflags=nodocs  $INSTALL_PKGS && \
+    dnf -y --allowerasing distrosync && \
+    dnf install -y --setopt=tsflags=nodocs $INSTALL_PKGS && \
     rpm -V $INSTALL_PKGS && \
     perl -v | grep -qe "v$PERL_VERSION\." && echo "Found VERSION $PERL_VERSION" && \
     dnf -y clean all --enablerepo='*'
@@ -51,7 +52,7 @@
 # writeable as OpenShift default security model is to run the container under
 # random UID.
 RUN mkdir -p ${APP_ROOT}/etc/httpd.d && \
-    sed -i -f ${APP_ROOT}/etc/httpdconf-fed.sed /etc/httpd/conf/httpd.conf && \
+    sed -i -f ${APP_ROOT}/etc/httpdconf.sed /etc/httpd/conf/httpd.conf && \
     chmod -R og+rwx /var/run/httpd /run/mod_fcgid ${APP_ROOT}/etc/httpd.d && \
     chown -R 1001:0 ${APP_ROOT} && chmod -R ug+rwx ${APP_ROOT} && \
     rpm-file-permissions
```

Difference between C9S and C10S
```
$ diff -u Dockerfile.c9s Dockerfile.c10s
--- Dockerfile.c9s	2024-08-09 12:44:13
+++ Dockerfile.c10s	2024-08-09 12:45:28
@@ -1,4 +1,4 @@
-FROM quay.io/sclorg/s2i-base-c9s:c9s
+FROM quay.io/sclorg/s2i-base-c10s:c10s

 # This image provides a Perl 5.40 environment you can use to run your Perl applications.

@@ -26,13 +26,13 @@
       io.openshift.tags="builder,${NAME},${NAME}${PERL_SHORT_VER}","${NAME}-${PERL_SHORT_VER}" \
       io.openshift.s2i.scripts-url="image:///usr/libexec/s2i" \
       io.s2i.scripts-url="image:///usr/libexec/s2i" \
-      name="sclorg/${NAME}-${PERL_SHORT_VER}-c9s" \
+      name="sclorg/${NAME}-${PERL_SHORT_VER}-c10s" \
       com.redhat.component="${NAME}-${PERL_SHORT_VER}-container" \
       version="1" \
       com.redhat.license_terms="https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI" \
       maintainer="SoftwareCollections.org <sclorg@redhat.com>" \
       help="For more information visit https://github.com/sclorg/s2i-${NAME}-container" \
-      usage="s2i build <SOURCE-REPOSITORY> quay.io/sclorg/${NAME}-${PERL_SHORT_VER}-c9s:latest <APP-NAME>"
+      usage="s2i build <SOURCE-REPOSITORY> quay.io/sclorg/${NAME}-${PERL_SHORT_VER}-c10s:latest <APP-NAME>"

 # Deselect a default stream
 RUN INSTALL_PKGS="perl perl-devel mod_fcgid perl-App-cpanminus perl-FCGI patch" && \
```

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Let's retest it 

[test]

**Comment by phracek** [comment]
Switch back to distrosync:

[test]

**Review by jplesnik — APPROVED** [review]
The changes looks good for me.

**Pull request merged**
