### PR TITLE
Add Perl 5.30 with mod_fcgid for RHEL-8

### PR DESCRIPTION
**Pull request by ppisar**
5.30-mod_fcgid is built on Perl 5.30 and mod_fcgid from modules.

RHEL7 does not contain perl-FCGI. Thus 5.30-mod_fcgi is not supported
on RHEL7.

F33 and older Fedoras do not contain modular perl-FCGI. F34 does not
have s2i-base image. Thus 5.30-mod_fcgi is not supported on Fedora.

https://github.com/sclorg/s2i-perl-container/issues/195

### CODE REVIEW

**Comment by ppisar** [comment]
The image probably won't build because a UBI8 repository <https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/appstream/os> is missing vital modules. E.g. perl-IO-Socket-SSL:2.066.

**Comment by pkubatrh** [comment]
Could we do the "git cp/mv dance" described at https://github.com/sclorg/welcome/blob/master/contribution.md#adding-a-new-version ? So we always have the history in the last version.

>The image probably won't build because a UBI8 repository is missing vital modules.

Would you have the full list of rpms that are missing from ubi8? I can follow up on getting them added to the repository so the image builds

**Comment by ppisar** [comment]
The missing ones are perl-IO-Socket-SSL:2.066 and perl-libwww-perl:6.34
modularity modules. I've already reported the issue against a configuration of
the UBI composes.

**Comment by ppisar** [comment]
How can I disable checks for rhel7? This docker file won't work on RHEL 7. The commit contains .exclude-rhel7 file, but it seems ignored. Can I merge the commit in spite of the failing test?

**Comment by ppisar** [comment]
I made the git move dance. Although I think it's bad. It clutters the commit history and breaks a bisect.

**Comment by ppisar** [comment]
The tests failed for perl-526 that I did not touch at all. And they failed only on one of the RHEL versions. Last time the same code failed on the other RHEL version. The CI infrastructure is unreliable.

**Pull request merged**
