### PR TITLE
Add Perl 5.26 with mod_fcgid for RHEL-8 Beta

### PR DESCRIPTION
**Pull request by ppisar**
5.26-mod_fcgid differs from 5.26. 5.26 was built on Perl 5.26 and
mod_perl from RHSCL. 5.26-mod_fcgid is built on Perl 5.26 and
mod_fcgid from modules.

RHEL7 does not contain perl-FCGI. 5.26-mod_fcgid removed SCL
infrastructure. Thus 5.26-mod_fcgi is not supported on RHEL7.

F29 does not contain non-modular 5.26 and perl-FCGI for 5.26. F28
contains Perl 5.26, but mod_fcgid is broken there. Thus 5.26-mod_fcgi
is not supported on Fedora.

### CODE REVIEW

**Comment by pkubatrh** [comment]
Please `s/rhel8-beta/rhel8/` since the images are not part of rhel8 beta.

Additionally the rhel8 build is failing due to:
```
STEP 18: RUN mkdir -p ${APP_ROOT}/etc/httpd.d &&     sed -i -f ${APP_ROOT}/etc/httpdconf.sed /etc/httpd/conf/httpd.conf &&     chmod -R og+rwx /var/run/httpd /run/mod_fcgid ${APP_ROOT}/etc/httpd.d &&     chown -R 1001:0 ${APP_ROOT} && chmod -R ug+rwx ${APP_ROOT} &&     rpm-file-permissions
sed: couldn't open file /opt/app-root/etc/httpdconf.sed: No such file or directory
```

**Comment by ppisar** [comment]
Thanks for the review. I removed the beta suffix and added the forgotten ./root
directory.

**Comment by pkubatrh** [comment]
LGTM now thanks! Tests passed for me locally. No CI for rhel8 but lets run the rest of the tests to see if something breaks.

[test][test-openshift]

**Comment by pkubatrh** [comment]
Centos Openshift failure seems unrelated - rhel7 openshift suceeded so unlikely this is caused by updated common scripts.

Merging. Thanks!

**Comment by ppisar** [comment]
My commit reverted your common submodule update. And that probably caused rhel7 test failure. PR #157 should fix it.

**Pull request merged**
