### PR TITLE
Change RH required labels based on updated spec

### PR DESCRIPTION
**Pull request by hhorak**
For full spec, see https://github.com/projectatomic/ContainerApplicationGenericLabels/blob/master/vendor/redhat/labels.md

### CODE REVIEW

**Comment by ppisar** [comment]
On Tue, Dec 01, 2015 at 02:34:42AM -0800, Honza Horak wrote:
>   * Change RH required labels based on updated https://github.com/projectatomic/ContainerApplicationGenericLabels/blob/master/vendor/redhat/labels.md
> 
I'm fine with this change. What's OpenShift people's opinion? Is renaming the `Name' label to `name' acceptable for you?

-- Petr

**Comment by mfojtik** [comment]
@ppisar the only labels we care about are the k8s and openshift namespaced labels, so we have no problem changing that.

@hhorak is this still up to date with latest atomic 'standards'? If so I can merge it. Also @rhcarvalho was doing some cleanup of layers by combining the LABEL commands together, maybe worth sync with them  about that (and the other PR).

**Comment by rhcarvalho** [comment]
@mfojtik all equivalent PRs with the same content in other image repos were either closed or merged and reverted, because the build system doesn't support the new labels yet.

**Comment by hhorak** [comment]
Closing, since osbs does not allow these new specs yet.

**Pull request closed without merging**
