### PR TITLE
Fix description of test

### PR DESCRIPTION
**Pull request by michal-josef-spacek**
This is not running on OpenShift

### CODE REVIEW

**Review by zmiklank — APPROVED** [review]
LGTM, thanks. No test from `test/run` should run on OCP.

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Let's run the test because of dancer-ex updated master

[test-openshift]

**Review by phracek — APPROVED** [review]
LGTM. Also dancer-ex is fixed by https://github.com/sclorg/dancer-ex/pull/86

**Pull request merged**
